__version__ = "0.2.0"
__author__ = "Adrian Torres, Red Hat Product Security"
__contact__ = "atorresj@redhat.com"
__homepage__ = "https://github.com/RedHatProductSecurity/rhubarb/"
__keywords__ = "celery redis lock redlock mutex task lockable duplicate prevent"
