name: Test
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup service test containers
        run: docker-compose -f tests/compose.yml up -d
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements-testing.txt
      - name: Run tests
        run: tox
      - name: Bring down service test containers
        run: docker-compose -f tests/compose.yml down
