name: Test
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6399:6379
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements-testing.txt
      - name: Run tests
        run: tox
